## Numpy

In [17]:
import numpy as np

arr1 = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,3,4,5,66]])
arr2 = np.array([3,4,5,6,2])

#print(type(arr1))

#print(arr1.shape)
#arr1+arr2

#index

arr1[2][4]



np.int64(66)

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

print(arr1 + arr2)
print(arr1.dtype)


[ 6  8 10 12 14]
int64


In [15]:
#np.arange(0,10,2).reshape(5,1)

#np.ones((3,4))
#np.sqrt(4)
#np.exp(arr1)
#np.sin(arr1)
np.cos(arr1)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

## Data Types

In [14]:
#2^8 =128    -128 => 0 =>127

arr1 = np.array([1,3,2,4],dtype=np.int8)
#print(type(arr1))
print(arr1)
print(arr1.dtype)
print(f"{arr1.nbytes} bytes")

[1 3 2 4]
int8
4 bytes


In [ ]:
#float datatype
arr2 = np.array([2.1,3.,3.8,6.6,7.0] ,dtype=np.float16)
print(arr2)
print(arr2.dtype)
print(f"{arr2.nbytes} bytes")

[2.1 3.  3.8 6.6 7. ]
float16
10 bytes


In [ ]:
#float datatype using int datatype
arr1 = np.array([100,232,234,543,323], dtype=np.float16)
print(arr1)
print(arr1.nbytes)


[100. 232. 234. 543. 323.]
10


In [ ]:
#string datatype
arr1 = np.array([100,2432,234,543,323], dtype=np.str_)
print(arr1)
print(arr1.dtype)  #u4 show highest digit in an array U=>unique
print(f"{arr1.nbytes} bytes")



['100' '2432' '234' '543' '323']
<U4
80 bytes


In [31]:
arr=np.array(["goms" , "ram" , "vetri" ,"fazil"])
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes")

['goms' 'ram' 'vetri' 'fazil']
<U5
80 bytes


In [37]:
arr=np.array(["goms" , "ram" , "vetri" ,"fazil"],dtype="<U3")
print(arr)

['gom' 'ram' 'vet' 'faz']


## Bollean

In [ ]:
#without mention dtype also working compiler can take boolean data type
arr =np.array([True,False,True,True],dtype=np.bool_)
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes")

[ True False  True  True]
bool
4 bytes


## Object datatype

In [4]:
#ar = np.array([1,2,"goms",True])  default stored in string data type it can manage we can use OBJECT datatype

ar=np.array([1,2,"goms",True],dtype=object)
print(ar)
print(ar.dtype)
print(ar.nbytes)

[1 2 'goms' True]
object
32


## Datatype convertion

In [8]:
arr=np.array([0,2,3,4])
ar=arr.astype(np.bool_)
print(ar)
print(ar.dtype)
print(ar.nbytes)

[False  True  True  True]
bool
4


## multiDimension & Reshape

In [ ]:
#arr=np.array(1)  ---> zero dimension
#arr=np.array([1,2,3,4,5]) --->  one dienstion
#arr=np.array([1,2,3,4],[1,2,34,4])  --->two dimension
arr =np.array([
    [
    [1,2,3,4],
    [0,9,8,7],
    
] , 

[
    [1,2,3,4],
    [4,5,6,4]
]
   
])   #---> three dimension
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [0 9 8 7]]

 [[1 2 3 4]
  [4 5 6 4]]]
3


In [ ]:

# indexing
ar = np.array([
    [1,2,3,4] ,
    [5,3,4,2]
    ])
#if access number five means
print(ar[1][0])

#in three dimension
# layers ,rows ,columns
arr =np.array([
    [
    [1,2,3,4],
    [0,9,8,7],
    
] , 

[
    [1,2,3,4],
    [4,5,6,4]
]
   
]) 
print(arr[1][0][2])


#it can all multi dimension indexing
print(arr[1,0,2])
# shape 
print(arr.shape)
#reshape
# using -1 it can assign row or column autometically
print(arr.reshape(2,-1))


5
3
3
(2, 2, 4)
[[1 2 3 4 0 9 8 7]
 [1 2 3 4 4 5 6 4]]


##  Row Slicing

In [1]:
import numpy as np
arr =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#print(arr[0])  # zero base indexing 
#print(arr[-1]) # reverse base indexing or negative indexing
#print(arr[-2]) 


#print(arr[0:3:2]) # start -inclusive :  end - exclusive : steps
#print(arr[:1])
#print(arr[:-1]) # it cancel last row -> it ca behave normal indexing

print(arr[::-1])# it can revrese the matrix

[[7 8 9]
 [4 5 6]
 [1 2 3]]


## Column slicing

In [20]:
#print(arr)
#print(arr[:,0])  # it show 0th index column can print
#print(arr[:,::-1])  # it can also inclusive exclusive and steps are included in column
# i am try to slicing part of matrix
print(arr[1:3 ,0:2])

[[4 5]
 [7 8]]


## Arithmethic 

In [5]:
arr = np.array([40,50,60,70,80])
print(arr-5)
print(arr+5)
print(arr*5)
print(arr/5)
print(arr ** 2) #power value
brr =np.sqrt(arr) #square root value
print(np.round(brr)) #round off value
print(np.floor(brr)) #floor value --> lower value
print(np.ceil(brr)) #ceil value --> higher value

print(np.round(arr + brr)) 

# perforn cponstant value also
print(np.pi)
#cirumference 
print(2*np.pi*brr)

age = np.array([12,34,5,63,18,19])
print (age)
age[age < 18] =18
print(age)

[35 45 55 65 75]
[45 55 65 75 85]
[200 250 300 350 400]
[ 8. 10. 12. 14. 16.]
[1600 2500 3600 4900 6400]
[6. 7. 8. 8. 9.]
[6. 7. 7. 8. 8.]
[7. 8. 8. 9. 9.]
[46. 57. 68. 78. 89.]
3.141592653589793
[39.73835306 44.42882938 48.66934411 52.56889986 56.19851785]
[12 34  5 63 18 19]
[18 34 18 63 18 19]


## board casting

In [85]:
import numpy as np;
arr =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

#brr= np.array([1,2,3])
brr=np.array([[1],[2],[3]])
print(arr.shape)
print(brr.shape)

print(arr*brr) # it can only (3,3)(3,1) replecate 1 2 3 as row and column wise

(3, 3)
(3, 1)
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


## Functions

In [ ]:
#arr=np.zeros((2,2,2)) -->zeros
arr=np.ones((2,2,2)) #-->ones
arr=np.full((2,3),3) #fill the values using tuples
arr=np.eye(5)# identity matrix
arr=np.empty((2,3)) # assing in garbage value
arr=np.arange(0,100,3) # start , end , step
arr=np.linspace(0,100,6) #evenly seprated between 0 to 100
#print(arr)
#arr=np.sum(arr)
#print(np.mean(arr))
#print(np.median(arr))
print(np.min(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.argmax(arr))

brr=np.array([
    [1,2,3],
    [4,5,6]
])
print(np.sum(brr))
print(np.max(brr))
print(np.argmax(brr))
print(np.sum(brr,axis=1))




0.0
1166.6666666666667
0
5
21
6
5
[ 6 15]


## Filtering

In [69]:
arr=np.array([50,100,65,46,70])
print(arr[arr<=50])
p=arr[arr%2==0]
r=arr[(arr%2==0)|(arr<=50)]
print(p)
print(r)

arr =np.array([
    [1,2,3],
    [4,5,6]
])

even=arr[(arr%2==0) | ( arr==1)] # flatened single row changed
print(even)
even=np.where(arr%2==0 , arr ,0) #where condition is used to it can't be fattend
print(even)

[50 46]
[ 50 100  46  70]
[ 50 100  46  70]
[1 2 4 6]
[[0 2 0]
 [4 0 6]]


## Random Numbers

In [120]:
rng=np.random.default_rng() # instancious look like a function  #seed=1 also perform 
print(rng.integers(1,31))  # start inclusive , end exclucive
print(rng.integers(low=1,high=31,size =(2,3)))
print(np.random.uniform(low=-1,high=1,size=5))

arr=np.array(["goms","shiva","io"])
rng.shuffle(arr)
print(arr)
print(rng.choice(arr))

4
[[15  4 20]
 [ 1  1 20]]
[ 0.42549625 -0.08713348  0.48755227 -0.06817247 -0.76170892]
['shiva' 'io' 'goms']
shiva


## File Handling

In [1]:
import os
print(os.getcwd())
import numpy as np

arr = np.array([1,2,3,4,5])
np.save("data.npy",arr)
read=np.load("data.npy")
print(read)

brr =np.array([6,7,8,9,0])
np.savez("data.npz" ,arr ,brr)
read=np.load("data.npz")
print(read)
print(read["arr_0"])
print(read["arr_1"])


c:\Users\sathi\OneDrive\Desktop\Data analysis\venv
[1 2 3 4 5]
NpzFile 'data.npz' with keys: arr_0, arr_1
[1 2 3 4 5]
[6 7 8 9 0]


## Linear Algebra

In [119]:
a =np.array([
    [1,2],
    [3,4]
])

b=np.array([
    [4,2],
    [3,4]
])
print(np.matmul(a,b))
print(b.T)

a=np.array([1,2,3])
b=np.array([4,2,3])
print(np.dot(a,b))





[[10 10]
 [24 22]]
[[4 3]
 [2 4]]
17
